name: Pipeline

on:
    push:
        branches: ["main"]
        
    repository_dispatch:
        types: [Pipeline]
        
    workflow_dispatch:
    
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        
            - name: Checkout
              uses: actions/checkout@v3

            # - name: Configurar aws cli
            #   run: |
            #       sudo apt install -y awscli
            #       aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
            #       aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            #       aws configure set default_region_name ${{ secrets.AWS_DEFAULT_REGION_NAME }}
            #       aws configure set default_output_format JSON
                  
            # - name: Inicializar o terraform
            #   run: cd terraform && terraform init

            # - name: Executar o script terraform
            #   run: cd terraform && terraform apply -auto-approve

            - name: Criar tabelas
              run: |
                  sudo apt install mysql-client-core-8.0
                  mysql -u ${{ secrets.RDS_DATABASE_USER }} -p ${{ secrets.RDS_DATABASE_PASSWORD }} -h dbpostech.cellpkbax23y.us-east-1.rds.amazonaws.com < scripts-database/data/criacao_tabelas.sql
